## Github issue: Make new variable that is just weeks past release date of phone

Overall steps we can do to make this happen:
- get info on when phones were released
- create new column for phone releaase date
- from the release date column, calculate the number of weeks since release data

### First, let's get information on the release dates of all the iphones.

(Source: https://www.bankmycell.com/blog/iphone-evolution-timeline-chart#text)

 - iPhone 4S: October 14, 2011 
 - iPhone 5: September 21, 2012 
 - iPhone 5S & 5C: September 20, 2013 
 - iPhone 6 & 6 Plus: September 19, 2014
 - iPhone 6S & 6S Plus: September 19, 2015 
 - iPhone SE: March 31, 2016 
 - iPhone 7 & 7 Plus: September 16, 2016 
 - iPhone 8 & 8 Plus: September 22, 2017 
 - iPhone X: November 3, 2017 
 - iPhone XS, XS Max: September 21, 2018 
 - iPhone XR: October 26, 2018
 - iPhone 11, Pro, Pro Max: September 20, 2019 
 - iPhone 12, Mini, Pro, Pro Max: November 13, 2020 
 - iPhone 13, Mini, Pro, Pro Max: September 24, 2021 
 - iPhone SE 3 (2022): March 18, 2022 
 - iPhone 14, Pro, Pro Max: September 16, 2022 
 - iPhone 14 Plus: October 6, 2022

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime as dt

In [4]:
%cd ../../../../data/p_dsi/teams2023/team1

/gpfs52/data/p_dsi/teams2023/team1

In [5]:
#read in data from xlsx file
df = pd.read_excel('combined_phone_data.xlsx')
df

,phone model,phone size,phone color,claim,weeks_monday,Year,Month,brand,model,generation,week_of_month,month,year
0,alcatel axel,32gb,black,1,2022-01-24,2022,1,alcatel,axel,NaN,4,1,2022
1,alcatel axel,32gb,black,3,2022-11-14,2022,11,alcatel,axel,NaN,2,11,2022
2,alcatel axel,32gb,black,1,2022-11-21,2022,11,alcatel,axel,NaN,3,11,2022
3,alcatel axel,32gb,black,3,2022-11-28,2022,11,alcatel,axel,NaN,4,11,2022
4,alcatel axel,32gb,black,1,2022-12-12,2022,12,alcatel,axel,NaN,2,12,2022
5,alcatel smartflip 4052r,4gb,black,1,2022-07-04,2022,7,alcatel,smartflip,4052r,1,7,2022
6,alcatel smartflip 4052r,4gb,black,1,2022-07-25,2022,7,alcatel,smartflip,4052r,4,7,2022
7,alcatel smartflip 4052r,4gb,black,3,2022-08-01,2022,8,alcatel,smartflip,4052r,1,8,2022
8,alcatel smartflip 4052r,4gb,black,1,2022-08-08,2022,8,alcatel,smartflip,4052r,2,8,2022
9,alcatel smartflip 4052r,4gb,black,1,2022-08-15,2022,8,alcatel,smartflip,4052r,3,8,2022
10,alcatel smartflip 4052r,4gb,black,2,2022-08-29,2022,8,alcatel,smartflip,4052r,5,8,2022
11,alcatel smartflip 4052r,4gb,black,1,2022-09-05,2022,9,alcatel,smartflip,4052r,1,9,2022
12,alcatel smartflip 4052r,4gb,black,3,2022-09-19,2022,9,alcatel,smartflip,4052r,3,9,2022
13,alcatel smartflip 4052r,4gb,black,3,2022-09-26,2022,9,alcatel,smartflip,4052r,4,9,2022
14,alcatel smartflip 4052r,4gb,black,4,2022-10-10,2022,10,alcatel,smartflip,4052r,2,10,2022
15,alcatel smartflip 4052r,4gb,black,1,2022-10-17,2022,10,alcatel,smartflip,4052r,3,10,2022
16,alcatel smartflip 4052r,4gb,black,3,2022-10-31,2022,10,alcatel,smartflip,4052r,5,10,2022
17,alcatel smartflip 4052r,4gb,black,2,2022-11-07,2022,11,alcatel,smartflip,4052r,1,11,2022
18,alcatel smartflip 4052r,4gb,black,3,2022-11-14,2022,11,alcatel,smartflip,4052r,2,11,2022
19,alcatel smartflip 4052r,4gb,black,2,2022-11-21,2022,11,alcatel,smartflip,4052r,3,11,2022
20,alcatel smartflip 4052r,4gb,black,1,2022-11-28,2022,11,alcatel,smartflip,4052r,4,11,2022
21,alcatel smartflip 4052r,4gb,black,2,2022-12-05,2022,12,alcatel,smartflip,4052r,1,12,2022
22,alcatel smartflip 4052r,4gb,black,5,2022-12-12,2022,12,alcatel,smartflip,4052r,2,12,2022
23,alcatel smartflip 4052r,4gb,black,1,2022-12-19,2022,12,alcatel,smartflip,4052r,3,12,2022
24,alcatel smartflip 4052r,4gb,black,4,2022-12-26,2022,12,alcatel,smartflip,4052r,4,12,2022
25,alcatel smartflip 4052r,4gb,black,1,2023-01-02,2023,1,alcatel,smartflip,4052r,1,1,2023
26,alcatel smartflip 4052r,4gb,black,1,2023-01-09,2023,1,alcatel,smartflip,4052r,2,1,2023
27,alcatel smartflip 4052r,4gb,black,1,2023-01-16,2023,1,alcatel,smartflip,4052r,3,1,2023
28,alcatel tetra,16gb,black,1,2022-08-01,2022,8,alcatel,tetra,NaN,1,8,2022
29,alcatel tetra,16gb,black,1,2022-11-21,2022,11,alcatel,tetra,NaN,3,11,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...
26631,samsung galaxy z fold3,256gb,silver,10,2022-06-27,2022,6,samsung,galaxy,z,4,6,2022
26632,samsung galaxy z fold3,256gb,silver,13,2022-07-04,2022,7,samsung,galaxy,z,1,7,2022
26633,samsung galaxy z fold3,256gb,silver,7,2022-07-11,2022,7,samsung,galaxy,z,2,7,2022
26634,samsung galaxy z fold3,256gb,silver,1,2022-07-18,2022,7,samsung,galaxy,z,3,7,2022
26635,samsung galaxy z fold3,256gb,silver,2,2022-07-25,2022,7,samsung,galaxy,z,4,7,2022
26636,samsung galaxy z fold3,256gb,silver,5,2022-08-01,2022,8,samsung,galaxy,z,1,8,2022
26637,samsung galaxy z fold3,256gb,silver,2,2022-09-12,2022,9,samsung,galaxy,z,2,9,2022
26638,samsung galaxy z fold3,256gb,silver,2,2022-09-19,2022,9,samsung,galaxy,z,3,9,2022
26639,samsung galaxy z fold3,256gb,silver,5,2022-09-26,2022,9,samsung,galaxy,z,4,9,2022
26640,samsung galaxy z fold3,256gb,silver,12,2022-10-03,2022,10,samsung,galaxy,z,1,10,2022
26641,samsung galaxy z fold3,256gb,silver,4,2022-10-17,2022,10,samsung,galaxy,z,3,10,2022
26642,samsung galaxy z fold3,256gb,silver,26,2022-10-24,2022,10,samsung,galaxy,z,4,10,2022
26643,samsung galaxy z fold3,256gb,silver,18,2022-10-31,2022,10,samsung,galaxy,z,5,10,2022
26644,samsung galaxy z fold3,256gb,silver,12,2022-11-07,2022,11,samsung,galaxy,z,1,11,2022
26645,samsung galaxy z fold3,256gb,silver,17,2022-11-14,2022,11,samsung,galaxy,z,2,11,2022
26646,samsung galaxy z fold3,256gb,silver,14,2022-11-21,2022,11,samsung,galaxy,z,3,11,2022
26647,samsung galaxy z fold3,256gb,silver,11,2022-11-28,2022,11,samsung,galaxy,z,4,11,2022
26648,samsung galaxy z fold3,256gb,silver,11,2022-12-05,2022,12,samsung,galaxy,z,1,12,2022
26649,samsung galaxy z fold3,256gb,silver,1,2022-12-12,2022,12,samsung,galaxy,z,2,12,2022
26650,samsung galaxy z fold3,256gb,silver,10,2022-12-19,2022,12,samsung,galaxy,z,3,12,2022
26651,samsung galaxy z fold3,256gb,silver,15,2022-12-26,2022,12,samsung,galaxy,z,4,12,2022
26652,samsung galaxy z fold3,256gb,silver,16,2023-01-02,2023,1,samsung,galaxy,z,1,1,2023
26653,samsung galaxy z fold3,256gb,silver,22,2023-01-09,2023,1,samsung,galaxy,z,2,1,2023
26654,samsung galaxy z fold3,256gb,silver,14,2023-01-16,2023,1,samsung,galaxy,z,3,1,2023
26655,samsung galaxy z fold3,256gb,silver,12,2023-01-23,2023,1,samsung,galaxy,z,4,1,2023
26656,samsung galaxy z fold3,256gb,silver,17,2023-01-30,2023,1,samsung,galaxy,z,5,1,2023
26657,samsung galaxy z fold3,256gb,silver,26,2023-02-06,2023,2,samsung,galaxy,z,1,2,2023
26658,samsung galaxy z fold3,256gb,silver,4,2023-02-13,2023,2,samsung,galaxy,z,2,2,2023
26659,samsung galaxy z fold3,512gb,black,61,2023-02-06,2023,2,samsung,galaxy,z,1,2,2023
26660,samsung galaxy z fold3,512gb,black,16,2023-02-13,2023,2,samsung,galaxy,z,2,2,2023

First, let's see what generations of iphone are included in the dataset.

In [102]:
#show the unique values in the column generation for the brand apple
df[df['brand'] == 'apple']['generation'].unique()

array(['11', '12', '13', '14', '3g', '4', '4s', '5', '5c', '5s', '6',
       '6s', '7', '8', 'se', 'x', 'xr', 'xs'], dtype=object)

Now let's create a new column called 'release' which will contain the date of release for each iphone, respectively.

In [103]:
#add a new column in df called release 
df['release'] = np.nan

In [104]:
#make the release column a datetime object
df['release'] = pd.to_datetime(df['release'])
df

,Unnamed: 0,phone model,phone size,phone color,claim,weeks_monday,Year,Month,brand,model,generation,week_of_month,month,year,release
0,0,alcatel axel,32gb,black,1,2022-01-24,2022,1,alcatel,axel,NaN,4,1,2022,NaT
1,1,alcatel axel,32gb,black,3,2022-11-14,2022,11,alcatel,axel,NaN,2,11,2022,NaT
2,2,alcatel axel,32gb,black,1,2022-11-21,2022,11,alcatel,axel,NaN,3,11,2022,NaT
3,3,alcatel axel,32gb,black,3,2022-11-28,2022,11,alcatel,axel,NaN,4,11,2022,NaT
4,4,alcatel axel,32gb,black,1,2022-12-12,2022,12,alcatel,axel,NaN,2,12,2022,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26656,26656,samsung galaxy z fold3,256gb,silver,17,2023-01-30,2023,1,samsung,galaxy,z,5,1,2023,NaT
26657,26657,samsung galaxy z fold3,256gb,silver,26,2023-02-06,2023,2,samsung,galaxy,z,1,2,2023,NaT
26658,26658,samsung galaxy z fold3,256gb,silver,4,2023-02-13,2023,2,samsung,galaxy,z,2,2,2023,NaT
26659,26659,samsung galaxy z fold3,512gb,black,61,2023-02-06,2023,2,samsung,galaxy,z,1,2,2023,NaT
26660,26660,samsung galaxy z fold3,512gb,black,16,2023-02-13,2023,2,samsung,galaxy,z,2,2,2023,NaT

In [105]:
#what are the unique generations of phones that we have?
df['phone model'].unique()

array(['alcatel axel', 'alcatel smartflip 4052r', 'alcatel tetra',
       'apple iphone 11', 'apple iphone 12', 'apple iphone 13',
       'apple iphone 14', 'apple iphone 3g s', 'apple iphone 4',
       'apple iphone 4s', 'apple iphone 5', 'apple iphone 5s',
       'apple iphone 6', 'apple iphone 6s', 'apple iphone 7',
       'apple iphone 8', 'apple iphone se', 'apple iphone se 2020',
       'apple iphone se 2022', 'apple iphone x', 'apple iphone xr',
       'apple iphone xs', 'at t cingular flip iv', 'google pixel 4',
       'google pixel 4a', 'google pixel 5', 'google pixel 6',
       'kyocera duraforce pro 2', 'lg arena 2', 'lg g6 duo',
       'lg g8 thinq', 'lg g8x thinq', 'lg k30', 'lg k40', 'lg k92',
       'lg neon', 'lg phoenix 5', 'lg prime 2', 'lg stylo 4',
       'lg stylo 5', 'lg v40 thinq', 'lg v60 thinq', 'lg velvet',
       'lg wing', 'lg xpression plus 2', 'lg xpression plus 3',
       'motorola one  ace', 'nokia 3.1 a', 'red hydrogen one',
       'samsung galaxy a01', 'samsung galaxy a02s', 'samsung galaxy a10',
       'samsung galaxy a11', 'samsung galaxy a12', 'samsung galaxy a13',
       'samsung galaxy a32', 'samsung galaxy a51', 'samsung galaxy a52',
       'samsung galaxy a71', 'samsung galaxy fold',
       'samsung galaxy j2 dash', 'samsung galaxy j7',
       'samsung galaxy note 10', 'samsung galaxy note 20',
       'samsung galaxy note 5', 'samsung galaxy note 8',
       'samsung galaxy note 9', 'samsung galaxy s iii',
       'samsung galaxy s10', 'samsung galaxy s20',
       'samsung galaxy s20 fe', 'samsung galaxy s21',
       'samsung galaxy s21 fe', 'samsung galaxy s22', 'samsung galaxy s4',
       'samsung galaxy s6', 'samsung galaxy s7', 'samsung galaxy s8',
       'samsung galaxy s9', 'samsung galaxy z flip',
       'samsung galaxy z flip3', 'samsung galaxy z flip4',
       'samsung galaxy z fold2', 'samsung galaxy z fold3'], dtype=object)

For each generation of iphone, add the release date into the 'release' column

In [106]:
#iphone 3gs released on June 19, 2009
df.loc[df['phone model'] == 'apple iphone 3g s', 'release'] = '2009-06-19'

In [107]:
#iphone 4 released on 2010-06-24
df.loc[(df['brand'] == 'apple') & (df['generation'] == '4'), 'release'] = '2010-06-24'

In [108]:
#for phone_model iphone 4s, set the release date to 2011-10-14
df.loc[(df['brand'] == 'apple') & (df['generation'] == '4s'), 'release'] = '2011-10-14'

In [109]:
#for phone_model iphone 5, set the release date to 2012-09-21
df.loc[df['phone model'] == 'apple iphone 5', 'release'] = '2012-09-21'

In [110]:
#for phone model iphone 5s, set the release date to 2013-09-20
df.loc[df['phone model'] == 'apple iphone 5s', 'release'] = '2013-09-10'

In [111]:
#iphone 5s and 5c released on 2013-09-20
df.loc[df['phone model'] == 'apple iphone 5c', 'release'] = '2013-09-10'

In [112]:
#iphone 6 and 6 plus released on 2014-09-19
df.loc[(df['brand'] == 'apple') & (df['generation'] == '6'), 'release'] = '2014-09-19'

In [113]:
#iphone 6 and 6 plus released on 2014-09-19
df.loc[(df['brand'] == 'apple') & (df['generation'] == '6 plus'), 'release'] = '2014-09-19'

In [114]:
#for phone model iphone 6s, set the release date to 2015-09-15
df.loc[(df['brand'] == 'apple') & (df['generation'] == '6s'), 'release'] = '2015-09-15'

In [115]:
#iphone se march 31,2016
df.loc[(df['brand'] == 'apple') & (df['generation'] == 'se'), 'release'] = '2016-03-31'

In [116]:
#for brand apple and generation 7, in the column release, set the release date to 2016-09-16
df.loc[(df['brand'] == 'apple') & (df['generation'] == '7'), 'release'] = '2016-09-16'

In [117]:
#for brand apple and generation 8, in the column release, set the release date to 2017-09-22
df.loc[(df['brand'] == 'apple') & (df['generation'] == '8'), 'release'] = '2017-09-22'

In [118]:
#for brand apple and generation x, in the column release, set the release date to 2017-11-03
df.loc[(df['brand'] == 'apple') & (df['generation'] == 'x'), 'release'] = '2017-11-03'

In [119]:
#for brand apple and generation xr, in the column release, set the release date to 2018-10-26
df.loc[(df['brand'] == 'apple') & (df['generation'] == 'xr'), 'release'] = '2018-10-26'

In [120]:
#for brand apple and generation xs, in the column release, set the release date to 2018-09-21
df.loc[(df['brand'] == 'apple') & (df['generation'] == 'xs'), 'release'] = '2018-09-21'

In [121]:
#for brand apple and generation 11, in the column release, add the value 2019-09-20
df.loc[(df['brand'] == 'apple') & (df['generation'] == '11'), 'release'] = '2019-09-20'

In [122]:
#for brand apple and generation 12, in the column release, add the value 2020-11-13
df.loc[(df['brand'] == 'apple') & (df['generation'] == '12'), 'release'] = '2020-11-13'

In [123]:
#for brand apple and generation 13, in the column release, add the value 2021-09-24
df.loc[(df['brand'] == 'apple') & (df['generation'] == '13'), 'release'] = '2021-09-24'

In [124]:
#for brand apple and generation 14, in the column release, add the value 2022-09-16
df.loc[(df['brand'] == 'apple') & (df['generation'] == '14'), 'release'] = '2022-09-16'

In [125]:
#for brand apple and generation 14 plus, in the column release, add the value 2022-10-06
df.loc[(df['brand'] == 'apple') & (df['generation'] == '14 plus'), 'release'] = '2022-10-06'

Let's check that everything worked.

In [126]:
#filter just brand apple
apple = df[df['brand'] == 'apple']
apple

,Unnamed: 0,phone model,phone size,phone color,claim,weeks_monday,Year,Month,brand,model,generation,week_of_month,month,year,release
32,32,apple iphone 11,128gb,black,111,2021-06-28,2021,6,apple,iphone,11,4,6,2021,2019-09-20
33,33,apple iphone 11,128gb,black,319,2021-07-05,2021,7,apple,iphone,11,1,7,2021,2019-09-20
34,34,apple iphone 11,128gb,black,320,2021-07-12,2021,7,apple,iphone,11,2,7,2021,2019-09-20
35,35,apple iphone 11,128gb,black,305,2021-07-19,2021,7,apple,iphone,11,3,7,2021,2019-09-20
36,36,apple iphone 11,128gb,black,269,2021-07-26,2021,7,apple,iphone,11,4,7,2021,2019-09-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17906,17906,apple iphone xs,64gb,silver,18,2023-01-16,2023,1,apple,iphone,xs,3,1,2023,2018-09-21
17907,17907,apple iphone xs,64gb,silver,19,2023-01-23,2023,1,apple,iphone,xs,4,1,2023,2018-09-21
17908,17908,apple iphone xs,64gb,silver,14,2023-01-30,2023,1,apple,iphone,xs,5,1,2023,2018-09-21
17909,17909,apple iphone xs,64gb,silver,13,2023-02-06,2023,2,apple,iphone,xs,1,2,2023,2018-09-21
17910,17910,apple iphone xs,64gb,silver,1,2023-02-13,2023,2,apple,iphone,xs,2,2,2023,2018-09-21

Checking if there are any missing values:

In [127]:
#check for null values in release column
apple['release'].isnull().sum()

0

In [128]:
#display the unique generation that have null values
apple[apple['release'].isnull()]['generation'].unique()

array([], dtype=object)

In [129]:
#display the rows that have null values in the release column
apple[apple['release'].isnull()]

Empty DataFrame
Columns: [Unnamed: 0, phone model, phone size, phone color, claim, weeks_monday, Year, Month, brand, model, generation, week_of_month, month, year, release]
Index: []

Great! We have 0 missing values, which means that each generation of iphone has a release date inputted.

In [138]:
#find the min and max dates in the column weeks_monday

df['weeks_monday'].min()

Timestamp('2021-06-28 00:00:00')

** Note ** : it's been 21 weeks since the iphone 14 was released on October 6, 2022. (As of March 5.)
Our most recent data point is February 13, 2023.
There are 18 weeks between the release of the iphone 14 and our most recent data point, and we are expected to predict 4 more weeks (22 in total.)

Our oldest data point is June 28th, 2021.
Because the iphone 13 and SE were released in 2021, we will have behavior on their first 30 weeks since release. These are the only models that we have for this. If this is the direction our model is headed in, we need to check the amount of data we have for those two ihpones.

Now we need to create a column that has the weeks since the release of the iphone generation. This will be calculated by our newest weeks_monday date, February 13, 2022, minus the release date. The goal of this is for us to be able to see the behavior of claims since the release of the iphone.

In [139]:
#create a new column called weeks_since_release
df['weeks_since_release'] = np.nan

#make the column weeks_since_release a datetime object
df['weeks_since_release'] = pd.to_datetime(df['weeks_since_release'])

,Unnamed: 0,phone model,phone size,phone color,claim,weeks_monday,Year,Month,brand,model,generation,week_of_month,month,year,release,weeks_since_release
0,0,alcatel axel,32gb,black,1,2022-01-24,2022,1,alcatel,axel,NaN,4,1,2022,NaT,NaT
1,1,alcatel axel,32gb,black,3,2022-11-14,2022,11,alcatel,axel,NaN,2,11,2022,NaT,NaT
2,2,alcatel axel,32gb,black,1,2022-11-21,2022,11,alcatel,axel,NaN,3,11,2022,NaT,NaT
3,3,alcatel axel,32gb,black,3,2022-11-28,2022,11,alcatel,axel,NaN,4,11,2022,NaT,NaT
4,4,alcatel axel,32gb,black,1,2022-12-12,2022,12,alcatel,axel,NaN,2,12,2022,NaT,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26656,26656,samsung galaxy z fold3,256gb,silver,17,2023-01-30,2023,1,samsung,galaxy,z,5,1,2023,NaT,NaT
26657,26657,samsung galaxy z fold3,256gb,silver,26,2023-02-06,2023,2,samsung,galaxy,z,1,2,2023,NaT,NaT
26658,26658,samsung galaxy z fold3,256gb,silver,4,2023-02-13,2023,2,samsung,galaxy,z,2,2,2023,NaT,NaT
26659,26659,samsung galaxy z fold3,512gb,black,61,2023-02-06,2023,2,samsung,galaxy,z,1,2,2023,NaT,NaT
26660,26660,samsung galaxy z fold3,512gb,black,16,2023-02-13,2023,2,samsung,galaxy,z,2,2,2023,NaT,NaT

In [143]:
#This will be calculated by our newest weeks_monday date, February 13, 2022, minus the release date.

#in the column weeks_since_release, subtract the release date from the weeks_monday date
df['weeks_since_release'] = df['weeks_monday'] - df['release']

#make weeks_since_release into the number of weeks and days
df['weeks_since_release'] = df['weeks_since_release'].dt.days / 7

In [145]:
#let's look at the apple dataframe
#filter just brand apple
apple = df[df['brand'] == 'apple']
apple

,Unnamed: 0,phone model,phone size,phone color,claim,weeks_monday,Year,Month,brand,model,generation,week_of_month,month,year,release,weeks_since_release
32,32,apple iphone 11,128gb,black,111,2021-06-28,2021,6,apple,iphone,11,4,6,2021,2019-09-20,92.428571
33,33,apple iphone 11,128gb,black,319,2021-07-05,2021,7,apple,iphone,11,1,7,2021,2019-09-20,93.428571
34,34,apple iphone 11,128gb,black,320,2021-07-12,2021,7,apple,iphone,11,2,7,2021,2019-09-20,94.428571
35,35,apple iphone 11,128gb,black,305,2021-07-19,2021,7,apple,iphone,11,3,7,2021,2019-09-20,95.428571
36,36,apple iphone 11,128gb,black,269,2021-07-26,2021,7,apple,iphone,11,4,7,2021,2019-09-20,96.428571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17906,17906,apple iphone xs,64gb,silver,18,2023-01-16,2023,1,apple,iphone,xs,3,1,2023,2018-09-21,225.428571
17907,17907,apple iphone xs,64gb,silver,19,2023-01-23,2023,1,apple,iphone,xs,4,1,2023,2018-09-21,226.428571
17908,17908,apple iphone xs,64gb,silver,14,2023-01-30,2023,1,apple,iphone,xs,5,1,2023,2018-09-21,227.428571
17909,17909,apple iphone xs,64gb,silver,13,2023-02-06,2023,2,apple,iphone,xs,1,2,2023,2018-09-21,228.428571
17910,17910,apple iphone xs,64gb,silver,1,2023-02-13,2023,2,apple,iphone,xs,2,2,2023,2018-09-21,229.428571

In [146]:
#filter the dataset to just weeks_since_release less than 50
apple = apple[apple['weeks_since_release'] < 50]

apple

,Unnamed: 0,phone model,phone size,phone color,claim,weeks_monday,Year,Month,brand,model,generation,week_of_month,month,year,release,weeks_since_release
3059,3059,apple iphone 12,128gb,black,14,2021-08-02,2021,8,apple,iphone,12,1,8,2021,2020-11-13,37.428571
3060,3060,apple iphone 12,128gb,black,43,2021-08-09,2021,8,apple,iphone,12,2,8,2021,2020-11-13,38.428571
3061,3061,apple iphone 12,128gb,black,57,2021-08-16,2021,8,apple,iphone,12,3,8,2021,2020-11-13,39.428571
3062,3062,apple iphone 12,128gb,black,65,2021-08-23,2021,8,apple,iphone,12,4,8,2021,2020-11-13,40.428571
3063,3063,apple iphone 12,128gb,black,59,2021-08-30,2021,8,apple,iphone,12,5,8,2021,2020-11-13,41.428571
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8002,8002,apple iphone 14,128gb,gold,50,2023-02-06,2023,2,apple,iphone,14,1,2,2023,2022-09-16,20.428571
8003,8003,apple iphone 14,128gb,gold,18,2023-02-13,2023,2,apple,iphone,14,2,2,2023,2022-09-16,21.428571
8004,8004,apple iphone 14,128gb,purple,68,2023-02-06,2023,2,apple,iphone,14,1,2,2023,2022-09-16,20.428571
8005,8005,apple iphone 14,128gb,purple,24,2023-02-13,2023,2,apple,iphone,14,2,2,2023,2022-09-16,21.428571
8006,8006,apple iphone 14,128gb,silver,1,2023-02-06,2023,2,apple,iphone,14,1,2,2023,2022-09-16,20.428571

In [8]:
#export the data to a xlsx file
df.to_excel('release_weeks_data.xlsx', index = False)